name: Run Code

on:
  schedule:
  - cron: "30 */5 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-code:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.7' # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      
      - name: Pull changes made by previous run
        run: |
          git pull origin master --allow-unrelated-histories

      - name: Run script
        run: |
          python main.pyw

      - name: Commit and push changes
        if: always()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Automated changes by GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
