name: Run Code

on:
  push:
    branches:
      - master

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.7' # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run script
        run: |
          python main.pyw
